### ISSUE TITLE
Resolution issue with swift-crypto package

### ISSUE THREAD

**Issue by sciencewithsteven** [soto-project/soto-cognito-authentication-kit#49]
Hello

When I add any of the 5.0.0 versions of the soto-cognito-authenticate-kit package and any 1.0.0 webauthn-swift package to my package manager there is a resolution issue between both packages over the versions of swift-crypto they use.

This is what my package manager package entries look like.
.package(url: "https://github.com/adam-fowler/soto-cognito-authentication-kit.git", from: "5.0.0-beta.1"),
.package(url: "https://github.com/swift-server/webauthn-swift.git", from: "1.0.0-alpha.2"),

If I only have soto-cognito-authentication-kit 5.0.0 alpha or beta in my package manager then swift-crypto resolves in my Package.resolved folder as version: 1.1.7

If I only have webauthn-swift 1.0.0-alpha.1 or 1.0.0-alpha.2 in my package manager then swift-crypto resolves to version: 3.4.0 in my Package.resolved folder. This is the latest version of swift-crypto. 

I did a 3rd test where I had omitted soto-cognito-authenticatio-kit from my package manager but kept in webauthn-swift and added other packages from vapor, hummingbird and the base soto package. The resulting swift-crypto version was 2.5.0 in my Package.resolved folder.

It seems like there might be a disconnect between the highest version of the swift-crypto package that soto-cognito-authentication-kit allows and the lowest version of the swift-crypto package that webauthn-swift allows which is at the heart of this resolution issue.

I'm using VSCode and this is the error I get. 

error: Dependencies could not be resolved because root depends on 'webauthn-swift' 1.0.0-alpha.2..<2.0.0 and root depends on 'soto-cognito-authentication-kit' 4.1.1..<5.0.0-beta.1.
'soto-cognito-authentication-kit' is incompatible with 'webauthn-swift' because 'webauthn-swift' 1.0.0-alpha.2 depends on 'swift-crypto' 2.0.0..<4.0.0 and no versions of 'webauthn-swift' match the requirement 1.0.0-alpha.2.0..<2.0.0.
'soto-cognito-authentication-kit' 4.1.1..<5.0.0-beta.1 practically depends on 'swift-crypto' 1.0.0..<2.0.0 because 'soto-cognito-authentication-kit' 5.0.0-alpha.1 depends on 'swift-crypto' 1.0.0..<2.0.0.
'soto-cognito-authentication-kit' {4.1.1..<5.0.0-alpha.1, 5.0.0-alpha.1.0..<5.0.0-beta.1} practically depends on 'swift-crypto' 1.0.0..<2.0.0 because no versions of 'soto-cognito-authentication-kit' match the requirement {4.1.2..<5.0.0-alpha.1, 5.0.0-alpha.1.0..<5.0.0-beta.1} and 'soto-cognito-authentication-kit' 4.1.1 depends on 'swift-crypto' 1.0.0..<2.0.0.

**Comment by adam-fowler** [comment]
The 5.0.0 release candidate I just released should fix this for you
